# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
