# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0002_data_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
