# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0003_auto_20171230_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='genesis',
            field=models.DateField(auto_now=True),
        ),
    ]
