# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0004_data_genesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='genesis',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
